# Generated by Django 5.0 on 2023-12-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='original_link',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
