# Generated by Django 5.0 on 2023-12-06 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallurl', '0002_alter_shortenedlink_original_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedlink',
            name='encrypted_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shortenedlink',
            name='short_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
