# Generated by Django 5.0 on 2023-12-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallurl', '0003_shortenedlink_encrypted_url_shortenedlink_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedlink',
            name='encrypted_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
